function [Y_pred, svmModel] = train_and_test_model(X_train, Y_train, X_test)
    svmModel = fitcsvm(X_train, Y_train, ...
                       'KernelFunction', 'rbf', ...
                       'KernelScale', 'auto', ...
                       'BoxConstraint', 1, ...
                       'Standardize', false);

    Y_pred = predict(svmModel, X_test);
end
